### ISSUE TITLE
Standardize code formatter

### ISSUE THREAD

**Issue by frankhart2018** [Documentive/TemplateBuddy#20]
We should standardize a code formatter, using different code formatted can result in unnecessary changes in PR which makes reviewing confusing.

**Comment by frankhart2018** [comment]
I use [Prettier](https://prettier.io/). @dhairyaj lmk what you use.

**Comment by dhairyaj** [comment]
I have prettier as well, but i think vscode used the default for js and ts. I will set it to prettier.

Closing this as prettier was decided as the code formatter to be used.
