### ISSUE TITLE
Setup basic react app

### ISSUE THREAD

**Issue by frankhart2018** [Documentive/TemplateBuddy#4]
Use `create-react-app`

**Comment by frankhart2018** [comment]
I can't add myself as an assignee for this, since I am not an admin yet, so adding it here. I'm picking this up.

**Comment by dhairyaj** [comment]
Made you the admin and also assigned this to you

**Comment by frankhart2018** [comment]
Since this was the first commit, I pushed it directly to master. Blocking pushes to master without PRs.
