### ISSUE TITLE
Handle Payload mismatch

### ISSUE THREAD

**Issue by dhairyaj** [Documentive/TemplateBuddy#94]
Requirement
- Return status code 409 if the payload does not match the section schema
- In the case of 409, no updates to the field
- Return the same resume without any changes

**Comment by frankhart2018** [comment]
On second thought, this would make it impossible to post some part of the schema to the backend to be saved, which is not ideal. This would mean that the data would be saved only when the user has filled in all the data for a particular section, which kind of makes our scheme of pushing data asynchronously futile based on diff between local storage copy and redux state copy.
